### ISSUE TITLE
Failed to compile at localhost (Mac)

### ISSUE THREAD

**Issue by sichokie** [space-dust-blockchain/eth-plot#116]
Hi, I'm sorry but I wanted to try this on my local, but I can't. The browser tab show the title but the terminal show these errors :

`ERROR in ./src/actionCreators/DataActions.ts
Module not found: Error: Can't resolve '../../gen-src/EthPlot' in '/Users/andika/eth-plot/src/actionCreators'
 @ ./src/actionCreators/DataActions.ts 13:18-50
 @ ./src/containers/App.tsx
 @ ./src/containers/Root.tsx
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:3000 (webpack)/hot/dev-server.js ./src/index.tsx

ERROR in ./src/actionCreators/Web3Actions.ts
Module not found: Error: Can't resolve '../../gen-src/typechain-runtime' in '/Users/andika/eth-plot/src/actionCreators'
 @ ./src/actionCreators/Web3Actions.ts 12:28-70
 @ ./src/containers/App.tsx
 @ ./src/containers/Root.tsx
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:3000 (webpack)/hot/dev-server.js ./src/index.tsx

ERROR in ./src/actionCreators/DataActions.ts
Module not found: Error: Can't resolve '../../gen-src/typechain-runtime' in '/Users/andika/eth-plot/src/actionCreators'
 @ ./src/actionCreators/DataActions.ts 12:28-70
 @ ./src/containers/App.tsx
 @ ./src/containers/Root.tsx
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:3000 (webpack)/hot/dev-server.js ./src/index.tsx`

And and the bottom it said failed to compile. Is there is something wrong? Thanks

**Comment by lbrendanl** [comment]
Hey @sichokie,

I don't think our README here is super clear apologies for the confusion.  

Can you try running `npm run build`?  You'll need that step after running npm install and before running npm start. 

Let me know if that fixes it for you.

**Comment by sichokie** [comment]
Great, everything is working! Just misleading a lil bit. Thank you!

**Comment by lbrendanl** [comment]
Thanks @sichokie glad to hear it. I'll update the README for clarity.
